/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mypower24.jcclustertest;

import com.mypower24.jcclustertest.customComp.LogTextArea;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.SwingUtilities;
import org.jcluster.core.JcManager;
import org.jcluster.core.test.JcTestIFace;

/**
 *
 * @author henry
 */
public class ExecutionTestPanle extends javax.swing.JPanel {

    JcTestIFace testIFace = JcManager.generateProxy(JcTestIFace.class);
    LogTextArea log;
    private final JcTestWindow jcTestWindow;

    /**
     * Creates new form ExecutionTestPanle
     */
    public ExecutionTestPanle(JcTestWindow w) {
        initComponents();
        log = (LogTextArea) jTextArea1;
        jcTestWindow = w;
        Map<String, Throwable> throwableMap = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExecRuntimeEx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbxException = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        spnIterCount = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spnIterDelay = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        btnExecBlockingCall = new javax.swing.JButton();
        spnBlockDuration = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnExecCustDataSize = new javax.swing.JButton();
        spnRetDataSize = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnExecThrowable = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbxThrowable = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new LogTextArea();
        spnThreadCount = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        prg = new javax.swing.JProgressBar();

        setMinimumSize(new java.awt.Dimension(500, 500));
        setName(""); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Throw RuntimeException"));

        btnExecRuntimeEx.setText("Exec");
        btnExecRuntimeEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecRuntimeExActionPerformed(evt);
            }
        });

        jLabel1.setText("Exception:");

        cmbxException.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbxException, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExecRuntimeEx))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnExecRuntimeEx)
                    .addComponent(cmbxException, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Iterations:");

        spnIterCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel3.setText("Iteration Delay [ms]:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Blocking Call"));

        btnExecBlockingCall.setText("Exec");
        btnExecBlockingCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecBlockingCallActionPerformed(evt);
            }
        });

        spnBlockDuration.setModel(new javax.swing.SpinnerNumberModel(5000, null, null, 500));

        jLabel4.setText("Block Duration [ms]:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnBlockDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExecBlockingCall))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnBlockDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnExecBlockingCall))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Custom Data Return Size"));

        btnExecCustDataSize.setText("Exec");
        btnExecCustDataSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecCustDataSizeActionPerformed(evt);
            }
        });

        spnRetDataSize.setModel(new javax.swing.SpinnerNumberModel(1024, 0, null, 1024));

        jLabel5.setText("Return Data Size [bytes]:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnRetDataSize, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExecCustDataSize))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnRetDataSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnExecCustDataSize))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Throw Throwable"));

        btnExecThrowable.setText("Exec");
        btnExecThrowable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecThrowableActionPerformed(evt);
            }
        });

        jLabel6.setText("Thowable:");

        cmbxThrowable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbxThrowable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExecThrowable))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnExecThrowable)
                    .addComponent(cmbxThrowable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        spnThreadCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel7.setText("Threads:");

        prg.setBorder(javax.swing.BorderFactory.createTitledBorder("Progress"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prg, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnThreadCount, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(spnIterDelay)
                            .addComponent(spnIterCount))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(spnThreadCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnIterCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnIterDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExecBlockingCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecBlockingCallActionPerformed

        runTest(() -> {
            for (int i = 0; i < (Integer) spnIterCount.getValue(); i++) {
                try {
                    long start = System.currentTimeMillis();
                    Object blockExec = testIFace.blockExec(getSelMemId(), (Integer) spnBlockDuration.getValue());
                    log.info("Blocking operation completed Thread: {} data: {} duration: {}ms", Thread.currentThread().getName(), blockExec, System.currentTimeMillis() - start);
                } catch (Exception e) {
                    log.info("Blocking call exception thread {} ex: {}", Thread.currentThread().getName(), e.getMessage());
                }
            }
        });
    }//GEN-LAST:event_btnExecBlockingCallActionPerformed

    private void btnExecCustDataSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecCustDataSizeActionPerformed
        getSelMemId();
        runTest(() -> {

            double totalSize = 0d;
            long totalDuration = 0l;
            long minDur = Long.MAX_VALUE;
            long maxDur = 0l;
            prg.setValue(0);
            btnExecCustDataSize.setEnabled(false);

            for (int i = 0; i < (Integer) spnIterCount.getValue(); i++) {
                try {
                    long start = System.currentTimeMillis();
                    byte[] customDataSize = testIFace.getCustomDataSize(getSelMemId(), (Integer) spnRetDataSize.getValue());
                    totalSize += customDataSize.length / (1024 * 1024d);
                    long dur = System.currentTimeMillis() - start;
                    totalDuration += dur;
                    if (minDur > dur) {
                        minDur = dur;
                    }
                    if (maxDur < dur) {
                        maxDur = dur;
                    }
                } catch (Exception e) {
                    log.info("Custom data size fail thread {} ex: {}", Thread.currentThread().getName(), e.getMessage());
                }
                int progress = (i + 1) / (Integer) spnIterCount.getValue() * 100;
                SwingUtilities.invokeLater(() -> prg.setValue(progress));
            }
            btnExecCustDataSize.setEnabled(true);
            int roundedSpeed = (int) (totalSize / (totalDuration / 1000d) * 100);
            
            log.info("Custom data size: {}MB  execTime: {}ms speed: {}MB/s min:{}ms max:{}ms", (int) totalSize, totalDuration, roundedSpeed / 100d, minDur, maxDur);
        });
    }//GEN-LAST:event_btnExecCustDataSizeActionPerformed

    private void btnExecThrowableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecThrowableActionPerformed
        runTest(() -> {

            for (int i = 0; i < (Integer) spnIterCount.getValue(); i++) {
                try {
                    long start = System.currentTimeMillis();
                    testIFace.throwEx(getSelMemId(), new Throwable("Throwable thrown and returned"));
                } catch (Exception e) {
                    log.info("Thread {} ex: {}", e.getMessage(), Thread.currentThread().getName());
                } catch (Throwable e) {
                    log.info("Thread {} ex: {}", e.getMessage(), Thread.currentThread().getName());
                }
            }
        });
    }//GEN-LAST:event_btnExecThrowableActionPerformed

    private void btnExecRuntimeExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecRuntimeExActionPerformed
        runTest(() -> {
            for (int i = 0; i < (Integer) spnIterCount.getValue(); i++) {
                try {
                    long start = System.currentTimeMillis();
                    testIFace.throwRuntimeEx(getSelMemId(), new RuntimeException("RuntimeException thrown and returned"));
                    log.info("Exec RuntimeException complete");
                } catch (Exception e) {
                    log.info("Thread {} ex: {}", e.getMessage(), Thread.currentThread().getName());
                }
            }
        });
    }//GEN-LAST:event_btnExecRuntimeExActionPerformed

    private void runTest(Runnable r) {
        List<Thread> tList = new ArrayList<>();
        for (int i = 0; i < (Integer) spnThreadCount.getValue(); i++) {
            Thread t = new Thread(r);
            t.setName("JC-TestExec-Thread-" + i);
            tList.add(t);
        }
        for (Thread thread : tList) {
            thread.start();
        }
    }

    private String getSelMemId() {
        if (jcTestWindow.getSelectedMember() == null) {
            throw new RuntimeException("No selected member");
        }
        return jcTestWindow.getSelectedMember().getDesc().getInstanceId();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecBlockingCall;
    private javax.swing.JButton btnExecCustDataSize;
    private javax.swing.JButton btnExecRuntimeEx;
    private javax.swing.JButton btnExecThrowable;
    private javax.swing.JComboBox<String> cmbxException;
    private javax.swing.JComboBox<String> cmbxThrowable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JProgressBar prg;
    private javax.swing.JSpinner spnBlockDuration;
    private javax.swing.JSpinner spnIterCount;
    private javax.swing.JSpinner spnIterDelay;
    private javax.swing.JSpinner spnRetDataSize;
    private javax.swing.JSpinner spnThreadCount;
    // End of variables declaration//GEN-END:variables
}
