/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mypower24.jcclustertest;

import ch.qos.logback.classic.Level;
import com.mypower24.jcclustertest.customComp.LogTextArea;
import com.mypower24.jcclustertest.tableModel.LoggerDescBean;
import com.mypower24.jcclustertest.tableModel.GenericBeanTableModel;
import com.mypower24.jcclustertest.tableModel.JTableModelDescription;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.ListSelectionModel;

/**
 *
 * @author henry
 */
public class LogPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = -2625218744240415637L;

    LogTextArea log;
    MissionControlMainWindow window;
    LoggerDescBean selectedLogger;
    Map<String, LoggerDescBean> loggerMap = new HashMap<>();

    GenericBeanTableModel<LoggerDescBean> loggersModel = new GenericBeanTableModel<>(
            new JTableModelDescription("Logger", "name"),
            new JTableModelDescription("Level", "levelStr")) {
        private static final long serialVersionUID = 1L;
    };

    /**
     * Creates new form ExecutionTestPanle
     *
     * @param w
     */
    public LogPanel(MissionControlMainWindow w) {
        initComponents();
        this.window = w;
        tblLoggers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void onSelectedLoggerChange() {
        int rowIdx = tblLoggers.getSelectedRow();
        if (rowIdx == -1) {
            return;
        }
        String lName = (String) tblLoggers.getValueAt(rowIdx, 0);
        selectedLogger = loggerMap.get(lName);
        cmbxLevel.setSelectedItem(selectedLogger.getLevelStr());
    }

    public void updateLoggerTable() {
        loggersModel.clear();

        try {

            Map<String, Integer> loggers = window.metricsMonitor.getLoggers(window.selectedMember.getId());
            if (loggers == null) {
                return;
            }
            loggerMap.clear();
            for (Map.Entry<String, Integer> entry : loggers.entrySet()) {
                String key = entry.getKey();
                Integer val = entry.getValue();
                loggerMap.put(key, new LoggerDescBean(key, val));
            }
            List<LoggerDescBean> collect = LoggerDescBean
                    .fromMap(loggers)
                    .stream()
                    .sorted((l1, l2) -> l1.getName().compareTo(l2.getName())).collect(Collectors.toList());
            loggersModel.add(collect);
        } catch (Exception e) {
            window.info(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblLoggers = new javax.swing.JTable();
        cmbxLevel = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 500));
        setName(""); // NOI18N

        tblLoggers.setModel(loggersModel);
        tblLoggers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblLoggersMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblLoggers);

        cmbxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(LoggerDescBean.getAllLevelsStr()));

        jButton1.setText("Set Level");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblLoggersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoggersMouseReleased
        onSelectedLoggerChange();
    }//GEN-LAST:event_tblLoggersMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        window.metricsMonitor.setLogLevel(window.selectedMember.getId(), selectedLogger.getName(), (Level.toLevel((String) cmbxLevel.getSelectedItem()).levelInt));
        updateLoggerTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbxLevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblLoggers;
    // End of variables declaration//GEN-END:variables
}
